PROBLEM WHEN CREATING AFTER DELETING SPOTIFY PLAYLIST MANUALLY
File "/mnt/c/Users/alber/Documents/Projects/playit-gcp/playit_api/repositories/audio_streaming/spotify_track_repository.py", line 38, in get_added_tracks
    assert response.status_code == 200


PROBLEM WHEN EMPTY TRACK LIST IS SENT FROM SCHEDULER TO SPOTIFY CLIENT
INFO:     127.0.0.1:57097 - "POST /playlists/0zn6oCm0Oenr2cFLyEdKVq/tracks HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]    
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)   
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/home/donalberton/.cache/pypoetry/virtualenvs/playit-api-IBrPdCJH-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/alber/Documents/Projects/playit-gcp/playit_api/main.py", line 66, in add_tracks
    playlist_repository.add_tracks(playlist_id, tracks)        
  File "/mnt/c/Users/alber/Documents/Projects/playit-gcp/playit_api/repositories/audio_streaming/spotify_playlist_repository.py", line 81, in add_tracks
    assert response.status_code == 201
AssertionError
INFO:     127.0